### ISSUE TITLE
Guardar progreso

### ISSUE THREAD

**Issue by omiras** [FOAP-NetMind-2022/beetlepush#18]
1. Seguir el ejemplo de CSS diner para guardar el progreso en localStorage
2. Para cada nivel, guardar:
   1. Si está completado
   2. El número de intentos que utilizado el usuario
   3. El código introducido por el usuario para poder precargarlo
 3. Cuando se cargue la app, hay que cargar la info de localStorage para determinar qué nieveles ya están superados. 
 4. Cuando un usuario acceda a un nivel en concreto, precargar el código JS que había introducido en el editor JS.

**Comment by omiras** [comment]
1. Investigar como usa actualmente el localStorage Beetlepush. Intentad entender como funciona.
2. Pensad en que modelo de datos necesitáis para guardar lo que pide issue. Pinta que hay que guardar un array de objetos, donde cada objeto contiene:
   1. Si está completado o no
   2. Un number con el número de intentos hasta completarlo
   3. Un string para guardar el último que ha intentado (o es ya el correcto) por parte del usuario

**Comment by omiras** [comment]
Primer punto: modificar el código para que ahora guarde también el JavaScript que el usuario ha introducido para intentar resolver el ejercicio

**Comment by omiras** [comment]
Segundo punto: Cuando acceda el usuario a un nivel nuevo, bien sea por las flechitas o por el menú, debéis mirar en localStorage si existe una entrada para ese nivel, y precargarle en el editor JavaScript el código que ya había introducido (tanto si ya estana correcto como si lo tenía a medias)

**Comment by omiras** [comment]
![Image](https://user-images.githubusercontent.com/3286458/187511298-0a070710-07b0-40c1-9001-1c44375a614f.png)

**Comment by omiras** [comment]
## Guardar progreso nuevo

## Actualizar progreso

## Resetear progreso

**Comment by victoriageeks** [comment]
## Guardar progreso nuevo

1. El usuario accede al nivel (x).
2. El usuario hace "click" en la sentencia _Type in an Array method_, es un apartado donde el usuario puede escribir la respuesta de cada nivel.
3. El fondo de la sentencia mencionada anteriormente, parpadeará en color _azul_ aunque el usuario previamente haya hecho "click" hasta que empiece a escribir su respuesta (sea correcta o incorrecta).
4. El usuario escribe un método de array y presiona el botón _enter_ situado a la derecha de la línea 1 en el _Javascript Editor_, o bien presiona _enter_ de su propio teclado. Su resultado es guardado independientemente esté bien o mal.

## Actualizar progreso
Si el usuario ha guardado correctamente su progreso mediante _enter_, puede avanzar por diferentes niveles aún siendo su respuesta incorrecta en niveles anteriores gracias a la flecha derecha situada en la barra de navegación en la parte superior-derecha. A continuación planteamos una simulación de una situación para actualizar el progreso:

1. El usuario no sabe la respuesta del nivel 1, su respuesta es _myGrass.x();_
2. El usuario avanza al nivel 2 aún siendo la respuesta del nivel 1 incorrecta.
3. El usuario vuelve al nivel 1 porque piensa que ya sabe el resultado de dicho nivel.
4. El usuario cuando accede al nivel 1, en la línea 1 del _Javascript Editor_ ve su resultado anterior _myGrass.x();
5. El usuario puede actualizar su respuesta borrando su respuesta anterior.
6. El usuario escribe la respuesta correcta _myGrass.push('ladybug');_ , ha actualizado la respuesta del nivel 1.
7. El usuario puede avanzar de nivel y si vuelve a acceder al nivel 1, puede ver su respuesta correcta pues fue la última que escribió.

*El usuario si ha puesto la respuesta correcta, cuando avanza de nivel, por ejemplo al 2, y vuelve al 1, no deja escribir y tampoco deja resetear el progreso, el usuario debe refrescar la página para realizar ambas funcionalidades.

## Resetear progreso

1. El usuario debe situarse en la barra de navegación donde explican los niveles en la parte superior derecha, y dar "click" al icono de 3 líneas.
2. La barra de navegación se actualizará y mostrará los niveles además de un botón que dice: _Reset progress_ .
3. El usuario debe dar "click" a dicho botón para resetear el progreso.

**Comment by omiras** [comment]
@thebadjavi Haz un clone nuevo del proyecto y prueba las funcionalidades de los test anteriores. Si alguno no lo entiendes, puedes preguntar a @victoriageeks . Cuando hayas finalizado, me informas a mí y aquí en un comentario, gracias!

**Comment by thebadjavi** [comment]
1.	He actualizado el proyecto lo he iniciado y el editor js en vez de poner “myGrass” pone  “undifined”, me sale en los 2 primeros niveles que yo ya tenia completados en los demás niveles que no he pasado aun me sale el texto correctamente de “myGrass”, Supongo que intenta cargar el contenido ya ejecutado anteriormente pero no esta guardado.



2.	En la zona de ayuda, el botón debería abrirse en una pestaña nueva solo en los primeros niveles

3.	El botón reset progress si haces f5 y vuelves a resetear no vacía el editor js, solo te lleva al lvl 1.

4.	Quizás tarda demasiado para cambiar de nivel

5.	Si hay un enter en blanco no lo valida como correcto
