### ISSUE TITLE
Ampliar estadísticas

### ISSUE THREAD

**Issue by omiras** [FOAP-NetMind-2022/beetlepush#22]
## Trabajo previo

- Verificar qué es lo que está funcionando en este momento, que documentos de MongoDB se están insertando

## Estadísticas básicas

- Para cada nivel, poder saber
  - el % de aciertos y fallos entre todos los intentos
  - tiempo que tarda el usuario en completar el nivel - segunda parte de la issue

## Herramientas

- Como primera, simplemente poder ver en el navegador el % de aciertos por nivel
- Como segunda implementación, simplemente hacer una tabla. Valorad usar software como este : https://bootstrap-table.com/docs/getting-started/introduction/
- Adicionalmente, crear un gráfico con La biblioteca Plotty de JavaScript
- Mirar si hay algún otro paquete de terceros en npm.js para usar en NodeJs.

## Diseño

- Debería ser acorde a la estética y estilos de las otras páginas PERO cuando las unifiquemos un poco.

## Opciones de implementación

1. Hacerlo todo con NodeJS. Es decir, hacemos un EJS tipo view-stats.ejs, que se renderiza al hacer /stats
2. Es un HTML como los demás, pero la biblioteca Plotty se alimenta de una petición GET del endpoint /get-stats

**Comment by SaraaLee** [comment]
######  INCORRECTS POR CADA NIVEL

Queremos calcular para cada nivel la media de número de intentos  de todos los usuarios para resolver ese nivel.

**Comment by omiras** [comment]
- Saber para cada día, cuantos ejercicios se han resuelto. 13/09 se han resuelto 25 ejercicios, 14/09 56. Un gráfico de tiempo, donde X son los días, Y el número de ejercicios resueltos
- El mínimo de caracteres que necesita un usuario para resolver un nivel determinado. Barras. X -> número de nivel, Y-> caracteres necesarios para completar el nivel
- Para cada nivel
   - Quitar el setTimeout
   - Aparece un cuadro con 5 mariquitas o similar para dar una puntuación de 1 a 5 , o elegir entre me ha gustado/no me ha gustado
   - Agregar también un boton de pasar nivel sin informar de nada
   - Modificar sendEvent para aceptar también la valoración del nivel y enviarlo en el POST
      - Modificar el modelo de Mongoose también. En todo caso, un number para la valoración

**Comment by Ste2812** [comment]
Revisar linea 12 app.js antes de merge
