### ISSUE TITLE
Mejoras UI/UX

### ISSUE THREAD

**Issue by omiras** [FOAP-NetMind-2022/beetlepush#26]
- Dar más protagonismo a la explicación del método de array en el level instructions . Cambiar estilos, mover la explicación del método al principio de la ventana de _Instructions_

**Comment by fataranto** [comment]
enlace al Figma, debería funcionar...
https://www.figma.com/file/tEBM37A47CmGZPiI8RW29h/BeetlePush-team-library

**Comment by omiras** [comment]
## Propuesta de bichos

1. @SaraaLee Podrías adjuntar en un zip en esta misma issue todos los bichos en .SVG?
2. Carol para cada bicho , y/o en conjunto, que se podría hacer para que tuvieran más consistencia

**Comment by lisis** [comment]
Gracias,

para realizar los comentarios adjunto todos los bichos en formato .png de 64x64px

[bichos.png.zip](https://github.com/FOAP-NetMind-2022/beetlepush/files/9549789/bichos.png.zip)

**Comment by omiras** [comment]
@fataranto @lisis Haced vuestra esta issue como parte del apartado de documentación del proyecto
