### ISSUE TITLE
Limpieza de CSS y código

### ISSUE THREAD

**Issue by omiras** [FOAP-NetMind-2022/beetlepush#27]
Necesitamos limpiar código de la práctica. Hay desde CSS que no se utiliza a JS que no se debería usar, como el envío de Google Analytics del programador de CSS Dinner

## CSS

- Eliminar las reglas CSS que ya no se utilizan, como por ejemplo: bento, pop, etc. Requiere análisis
- Refactorizar algunas clases como los bichos, que hay CSS copiado para definir los mismos estilos a diferentes tags (tipo las reglas CSS donde están los background image de los bichos. Pedir ayuda a @omiras 

## JS

- Eliminar Google Analytics, y en todos los sitios que se utilice (localStorage, etc)
- Renombrar el fichero restaurant.js a algo más acorde a nuestro proyecto : field.js, terrain.js, bugsfield.js
- Quitar tooltips y todos los eventos que no se usen

## Niveles de refactorización

- Os va a pasar que habrás cosas muy claras de quitar (tipo Google Analytics) y otras no tan claras. Os sugiero que ataquéis primero las más claras (un commit para cada una); y las que no veáis tan claras las podéis apuntar un comentario.

## Metodología

- Un commit por cada refactorización
- Después de cada cambio, probar el siguiente test manual
   1. Resetear progreso
   2. Escoger un nivel al azar
   3.  Hacerlo mal
   4. Resolverlo bien
   5. Comprobar que todo sigue funcionando haciendo hincapié en aquella parte que habéis cambiado

**Comment by Andreu-G** [comment]
> *... reglas CSS donde están los bacground image de los bichos.

Es bac**k**ground :)

**Comment by omiras** [comment]
Focalizad en la limpieza de JavaScript, puesto que se está rediseñando el CSS usando Bootstrap

**Comment by victoriageeks** [comment]
comentar el tema de <ladybug>, etiquetas en html eliminarlas
