### ISSUE TITLE
Documentación de las tecnologías usadas en la app

### ISSUE THREAD

**Issue by omiras** [FOAP-NetMind-2022/beetlepush#35]
- Hacer un esquema de las tecnologías usadas en la app, tipo https://github.com/FOAP-Netmind-2021/avisa-me#construido-con-%EF%B8%8F
- Para cada tecnología explicar un poco en qué consiste (que es NodeJS, que es MongoDB, como en el ejemplo)

**Comment by SaraaLee** [comment]
Si podéis ayudarme a completar la lista, ya que no estoy segura si éstas son todas las tecnologías

TECNOLOGIAS BEETLEPUSH

**DATABASE:** 
- MongoDB 

**BACK END / SERVER SIDE**
- Mongoose
- NPM
- NODE JS
- EXPRESS
- NODEMON

**FRONT END / CLIENT SIDE**
- BOOTSTRAP
- EJS
- CSS
- HTML 5
- JS
- PLOTLY

**CARTOON DESIGN???** _Es necesario poner con que se han hecho¿?_
- INKSCAPE

**Comment by Andreu-G** [comment]
**TRANSLATIONS**

- [18next](https://www.i18next.com)

En front end añadiría [jQuery ](https://jquery.com)también ;)

**Comment by omiras** [comment]
- EJS en este caso se usa como tecnología back end, dado que lo que le llega al cliente, es un HTML , no un EJS.
- JQuery es una tecnología del lado cliente, pues manipula el DOM y gestiona eventos, entre otras funcionalidades.

**Comment by Andreu-G** [comment]
> * JQuery es una tecnología del lado cliente, pues manipula el DOM y gestiona eventos, entre otras funcionalidades.

Cierto, me había olvidado que field.js, levels.js etc se cargan en el html

**Comment by thebadjavi** [comment]
el codeflask?

**Comment by SaraaLee** [comment]
Codeflask es del lado servidor no?

**Comment by omiras** [comment]
Sigue sin estar claro que forma parte de tecnología del lado servidor o lado cliente, veamos si estos dos apuntes ayudan. Os dejo un vídeo más abajo también interesante. 🐱‍👤

- El cliente es el navegador Web. Si puedes acceder a una biblioteca, funcionalidades, etc desde tu propio navegador, entonces es lado cliente. ¿Podemos acceder a las funcionalidades de CodeFlask desde el navegador? Sí. Son funcionalidades que se ejecutan una vez hemos recibido el HTML. Pasa lo mismo con Vue, JQuery, Bootstrap, Plotty.
![image](https://user-images.githubusercontent.com/3286458/191931018-b48b6bee-4544-4717-9cca-fde32af9e3b3.png)

- El servidor es la parte a la que no podemos acceder desde el navegador Web, e implementa una gran variedad de servicios. Por ejemplo, un servidor que recibe un pedido enviado desde la App de Glovo (una app del móvil TAMBIÉN puede ser un cliente). También, el endpoint de Google https://google.es/**search** ... La tecnología detrás del endpoint /search, puede ser variada (Python, Go, NodeJS, Java, etc); es lado servidor.

Más info:
https://www.youtube.com/watch?v=hJHvdBlSxug
