### ISSUE TITLE
Feedback after code is executed

### ISSUE THREAD

**Issue by omiras** [FOAP-NetMind-2022/beetlepush#45]
## Description

We need to improve the feedback we give to the user after exercise code is executed.

## Requirements

It would be a good idea, after executing the code, give a piece of information about what is just happened. The message could be in the bottom of the app, just below the Instructions and JavaScript Editor area. An easy way to implement this would be using Bootstrap's alert component: 

https://getbootstrap.com/docs/5.0/components/alerts/

### Exercise is correct

If the exercise is correct, display the evaluation of the exercise
![Image](https://user-images.githubusercontent.com/3286458/191061430-277dc294-b770-432c-b0c6-ff4a1b20ccaf.png)

### User's code throws error

If the user's code generated a syntax or execution error, make him know 

![Image](https://user-images.githubusercontent.com/3286458/191062104-8efc94b6-3cb6-4247-80d7-a3ecf60ac2b2.png)

There is a place in the code where we can catch the exception's error. Have a look at checlLevelCorrect function. 

![Image](https://user-images.githubusercontent.com/3286458/191062225-84d8848d-f558-4f8e-980f-5a39f9079513.png)

### Exercise not correct

If there is no error, but the exercise is not correct, make him know too. 
  1. User tries to solve the first problem, using pop method instead of push method
  2.Editor and Instructions section will play the stoke animation
  3. Additionally, display a warning with the value of the variable to be evaluated.

![Image](https://user-images.githubusercontent.com/3286458/191062930-9b776008-cd01-4abc-a5b0-08f1bc826482.png)

**Comment by omiras** [comment]
Expect to finish this issue today or tomorrow.

@fataranto  @lisis What do you think about design? I am using Bootstrap default colors.

![image](https://user-images.githubusercontent.com/3286458/192141925-106be357-8645-40ff-acf3-6f62b734ed8b.png)

![image](https://user-images.githubusercontent.com/3286458/192141888-8cfd613c-6020-4334-a36e-e7ea35ce2bf3.png)

![image](https://user-images.githubusercontent.com/3286458/192141942-55be8cff-d128-4ff9-968c-3d9f0061a095.png)

**Comment by fataranto** [comment]
We're still working on the style guide so don't worry, once you have the functionality finished I can adapt the way the message is displayed
