### ISSUE TITLE
Some translations are missing

### ISSUE THREAD

**Issue by omiras** [FOAP-NetMind-2022/beetlepush#47]
Please, finish the translations for the missing levels.
Translations for levels 6->15 are missing.

**Comment by Andreu-G** [comment]
I'd love to work on this, please assign it to me 🙂

**Comment by omiras** [comment]
@Andreu-G Hi! You really are ahead of me, I wanted to make a video to explain how to implement these issues xD.
Take a look at this [wiki](https://github.com/FOAP-NetMind-2022/beetlepush/wiki/C%C3%B3mo-asignarse-una-issue-y-realizarla); you can assign the issue to yourself and start doing this issue right away!

**Comment by Andreu-G** [comment]
Hahah! Alright, thanks!

**Comment by omiras** [comment]
@Andreu-G Level 5 instructions' are actually Level 6 instructions', please, check it out!
