### ISSUE TITLE
Remove unused code and files

### ISSUE THREAD

**Issue by omiras** [FOAP-NetMind-2022/beetlepush#48]
## Description

There are several files, functions and piece of code we don't really use. It would be nice to have a cleaner code so adding new features won't be so cumbersome.

## Requirements

These pieces of code and files should be removed. Additionally, some files should be modified. The list is not limited and may include other suggestions.

### Remove from code

- All the parts related to "hover" elements that would display the tags of _boardmarkup_ levels.js property. IT does not make sense. We can create then another issue to mimic this feature but in our project. 
![image](https://user-images.githubusercontent.com/3286458/191442614-b7cd62a6-c72b-41e8-96be-646f1e7519f8.png)
- PopupCenter function: not used anymore

As commented, please, be free to remove anything you figure out it's not used anymore.

### Files should be removed

- images/misc: all the images that are not used, even the whole folder
- *bak files, should have been ADD to the commit in the first place!
- css/jquery.mCustomScrollbar.css
- js/jquery.mCustomScrollbar.min.js
-  .vscode configuration file

### Files to be modified

- .gitignore: add .vscode foder 
- field.js and style.css. Some selector are not used anymore. The code for these selectors should be removed: 
  - .note-toggle
  - .level-menu-toggle-wrapper
  - #mCSB_2_container

**Comment by victoriageeks** [comment]
Hola, estoy con esta issue**
![image](https://user-images.githubusercontent.com/104619494/192108248-fbcfc885-c40a-40f9-82bf-6c47c1362716.png)
he conseguido que de <caterpillar></caterpillar> se muestre 'caterpillar'
![image](https://user-images.githubusercontent.com/104619494/192108281-f4386388-1917-47b5-9ba8-ebdf46881107.png)
y para cuando detecte 'grass' o 'brackets' no me lo muestre, sin embargo en la consola me sale un error diciendo helpertext.hide() is not a function. He estado investigando y .hide() funciona con selectores, y helpertext es una variable. Mi problema esta en como ocultar esa variable, ya que cogiendo el selector $(.helper).hide() sigue mostrandose grass o brackets. Helpertext no se lee como undefined, el problema está en como ocultar la variable si se lee como grass o brackets. Sigo investigando

**Comment by omiras** [comment]
Hi @victoriageeks ,

Thank you for taking care of this issue.

The problem is that we really must remove the feature and later, in another issue, rebuild it from the ground up.
Even if you manage to make it work, at the end of the day you are displaying **boardMarkUp**.

It may be helpful for this exercise but think about this one:

![image](https://user-images.githubusercontent.com/3286458/192140056-bea0a730-8092-4591-b302-84ca9112a7d2.png)

**Comment by omiras** [comment]
Hi @victoriageeks ,

Will you still work on this issue? If you can't spend any time on it, do not worry, I'll take it. I want to close this issue before moving to further improvements 😊

**Comment by omiras** [comment]
`$ for FILE in images/misc/*; do grep -rni $FILE *.html *.js *.css; done`

Provided you execute this command in *public* folder, it will _iterate all over the names of the files in images/misc folder". For each file, check if it is included in any file with extension HTML , CSS or JS _

Some bash commands allow us to check if a particular file is linked to another. We achieve this by combining "for" and "grep"
