### ISSUE TITLE
Crear página de About-US

### ISSUE THREAD

**Issue by omiras** [FOAP-NetMind-2022/beetlepush#5]
## Objetivo 

Crear la página de About US

## Análisis

- Escoger un template de una página About US 
https://github.com/bradtraversy/design-resources-for-developers#html--css-templates

La página debería contener la siguiente información

- Cada uno de los miembros del equipo
  - Foto? Poner un "placeholder" de momento
  - Linkedin y GitHub de cada uno. Para hacerlo fácil, sería bueno que en un comentario cada miembro escribe sus dos respectivas URLs 
 - Descripción de qué va el curso y el porqué de este proyecto
 - Crear una carpeta de nombre "about-us" y colocar toda la página Web ahí
 - En algún lugar del about-us un enlace al juego. ../index.html
 
Crear esta página de momento en una carpeta aparte y luego será integrada bien en la aplicación Front End o en NodeJS/Express

**Comment by omiras** [comment]
Por ejemplo: https://singulars2022.github.io/cinedebarrio-landingpage/

**Comment by omiras** [comment]
Icono para ir a la App del juego

![Image](https://user-images.githubusercontent.com/3286458/181582071-02eafeb3-f805-47ab-9472-20b15dba846e.jpg)

**Comment by victoriageeks** [comment]
[diseños](https://drive.google.com/drive/folders/1lTYK9YAjbo42IuvOEEEhT1IeujN4Mj5b?usp=sharing)

**Comment by victoriageeks** [comment]
Resumen breve 1 día: hemos optado por no usar una template por defecto. Se hace uso de html, css, js y bootstrap.  Se ha requerido códigos externos para realizar animaciones en el texto o en las cards, todos estos recursos están almacenados en el documento  recursos que está disponible en [diseños](https://drive.google.com/drive/u/1/folders/1lTYK9YAjbo42IuvOEEEhT1IeujN4Mj5b). Se ha realizado un boceto rápido, con una nav-bar navigation, cards para cada miembro, y un carrousel.

**Comment by victoriageeks** [comment]
Resumen breve día 2:  Se realiza un flex y se centraliza todo el contenido de la página about-us, se incluye una background-image acompañado de un gradient en toda la imagen, se implementa el footer y se añade la nueva sección "nuestra historia", pero necesita un cambio de fuente y color. A conseguir para el siguiente día: modificar el contenido de cada card, incluyendo los botones a las RRHH, arreglar el footer visualmente, el icono de Beetle Push desaparece de la nav-bar y se implementa como un elemento estático durante toda la experiencia de navegación abajo a la izquierda y finalmente, enlazar las secciones de la barra de navegación a su sitio correspondiente.

**Comment by victoriageeks** [comment]
@Ste2812 @Francesc1980 @fataranto @Andreu-G @thebadjavi @SaraaLee @lisis @omiras he grabado un vídeo explicando un poco el día 2,  y así recibir sugerencias para el about-page, gracias :) [link al vídeo](https://drive.google.com/file/d/1Lr_7V9MbyZYBaN0SIWfsJd6J_oy93Vd8/view?usp=sharing)

**Comment by omiras** [comment]
@victoriageeks Gracias por la explicación! A mi la verdad es que me gusta mucho pero mi gusto estético no es el mejor (ProGats). No sé que puede opinar @lisis . Lo que si que veo es que los colores que se usen aquí, sería bueno intentar usarlos también en el juego, no?

**Comment by omiras** [comment]
Acotamos la issue:

- Acabar las tarjetas. Se pide a TODOS los miembros del equipo que adjunten en un comentario su Linkedin, GitHub, la foto (si quieren) y una frase descriptiva. 
- El slider queda fuera
- Sección "Nuestra Historia" (baja prioiedad)
- Footer (baja prioridad)

**Comment by SaraaLee** [comment]
Para el about :

www.linkedin.com/in/srodriguezsan/
https://github.com/SaraaLee

Empezando en programación. Me encanta la Biología, los videojuegos y el café.

**Comment by omiras** [comment]
Para el about:

https://es.linkedin.com/in/oscar-miras-ortiz-2a65054a
https://github.com/omiras

**Foto**: de momento podéis poner una random
**Frase**: Primero resuelve el problema, después escribe el código (la he copiado, no estoy muy inspirado hoy, igual la cambio por algo más jaja)

**Comment by Francesc1980** [comment]
para el about: 

linkedin: https://www.linkedin.com/in/francesc-duran-granado-4134871a1
github :http://githb.com/Francesc1980

foto:
Frase: SIempre es bueno intentar hacer las cosas bien

**Comment by thebadjavi** [comment]
Para el about :

https://github.com/thebadjavi
https://www.linkedin.com/in/javi-fernandez-vazquez-11104641/

foto:
Frase: Es genial trabajar con ordenadores. No discuten, lo recuerdan todo y no se beben tu cerveza.

**Comment by Andreu-G** [comment]
[LinkedIn](https://www.linkedin.com/in/andreugm/)
[GitHub](https://github.com/Andreu-G)
Frase: Los errores son la prueba de que lo estás intentando.
Subo la foto más tarde.

**Comment by fataranto** [comment]
para el about:
linkedin: https://www.linkedin.com/in/fabiantaranto/
github; https://github.com/fataranto
Frase: La belleza de las cosas tal cual son

**Comment by lisis** [comment]
Para el about:

[GitHub](https://github.com/lisis)
[LinkedIn](https://www.linkedin.com/in/carolinalisa/)
Frase: Design and develop easy-to-use solutions

*Me falta buscar la imagen

**Comment by Ste2812** [comment]
Para el about:

https://www.linkedin.com/in/stefano-gallone-5843b8b9/
https://github.com/Ste2812

Frase: El momento y el lugar adecuado te llevan a estar donde tienes que estar ahora. En la vida los planes cambian mientras en la programación precisa y predecible, hay enormes posibilidades para crear. Chef y desarrollador en el alma.

**Comment by Ste2812** [comment]
en breve pondré foto también

**Comment by omiras** [comment]
- Poned el mismo bicho para todos en las cards #4 
- Si no tienes información de alguno de los miembros del equipo, ponéis un lorem de momento, y ya cada uno más adelante lo puede modificar
- Cuando penséis que está terminada la issue, avisad a @omiras

**Comment by fataranto** [comment]
foto...
![fabi](https://user-images.githubusercontent.com/5854537/182426204-70d8321f-468c-45c9-a228-645d3f3fcf1d.jpg)
